### ISSUE TITLE
Modelling improvements?

### ISSUE THREAD

**Issue by ashwinvis** [exabl/snek5000-abl#10]
- [x] clean freestream initial condition

- [x] constant SGS filter length scale ~ maximum grid spacing, $\Delta$, decrease $C_0$ in Smagorinsky model to 0.15 (#21)

- [x] Boundary condition: evaluate shear stress $\tau_w$ based on velocities at 3rd and 4th grid levels (#20)

- [x] Grid refinement: Non uniform elements in the vertical direction (master)
 
- [ ] ~~constant SGS viscosity sans wall damping~~

- [x] SGS wall damping function: Change power from 0.5 to 3.0 (#22)

Should add parameters to toggle this?
